# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitGpt < Formula
  desc ""
  homepage "https://github.com/ohmpatel1997/CommitGPT"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.2.0/CommitGPT_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d0136adaaca6072d17a19f1cf26573631cd0514663488133f2b88113858d1401"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.2.0/CommitGPT_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1bbd1d33d6c5b39665f47431a23a1b5c722b1185f4479bc1f953efd3e24040f7"

      def install
        bin.install "commit-gpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.2.0/CommitGPT_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "bdf48355a2df74cae97bc3996cdc7117afa0b581229646b51b9c716eeab24383"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.2.0/CommitGPT_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b8f567f8ecd442281f37d7444f9fa409cba8fb46b494260dee7ab59f85cb0dd6"

      def install
        bin.install "commit-gpt"
      end
    end
  end
end
