# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitGpt < Formula
  desc ""
  homepage "https://github.com/ohmpatel1997/commit-gpt"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohmpatel1997/commit-gpt/releases/download/v0.2.4/commit-gpt_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1c668a074e1419eea080c81ffe5c47df26897cbfa8ce6994c3df45cc2edca826"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/commit-gpt/releases/download/v0.2.4/commit-gpt_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f51dc4d7537162ea71ef415aa4f20ea994ef7b2d260cc4db9289e473b264c4bb"

      def install
        bin.install "commit-gpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmpatel1997/commit-gpt/releases/download/v0.2.4/commit-gpt_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7a8f6714a44fba725d525f313abc1ebc7d7eb9aa57f93c50d21abba3b200f15a"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/commit-gpt/releases/download/v0.2.4/commit-gpt_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5f653121186e6be9be9c99f923c3f2d28aa7556041eb5e6573d44fdb95304561"

      def install
        bin.install "commit-gpt"
      end
    end
  end
end
